pandoc decide_what_to_teach.md -o build/decide_what_to_teach.pdf
pandoc disruptive_behavior.md -o build/disruptive_behavior.pdf
pandoc engaging_coding_exercises.md -o build/engaging_coding_exercises.pdf
pandoc instant_feedback.md -o build/instant_feedback.pdf
pandoc prevent_install_failure.md -o build/prevent_install_failure.pdf
pandoc save_preparation_time.md -o build/save_preparation_time.pdf
pandoc self_study_material.md -o build/self_study_material.pdf
pandoc start_class.md -o build/start_class.pdf
pandoc storytelling.md -o build/storytelling.pdf
pandoc students_work_together.md -o build/students_work_together.pdf
