pandoc decide_what_to_teach.md -o doc/decide_what_to_teach.docx
pandoc disruptive_behavior.md -o doc/disruptive_behavior.docx
pandoc engaging_coding_exercises.md -o doc/engaging_coding_exercises.docx
pandoc instant_feedback.md -o doc/instant_feedback.docx
pandoc prevent_install_failure.md -o doc/prevent_install_failure.docx
pandoc save_preparation_time.md -o doc/save_preparation_time.docx
pandoc self_study_material.md -o doc/self_study_material.docx
pandoc start_class.md -o doc/start_class.docx
pandoc storytelling.md -o doc/storytelling.docx
pandoc students_work_together.md -o doc/students_work_together.docx
